version: "3"
services:
  zookeeper:
    image: ubuntu/zookeeper
    ports: 
    - "2181:2181"
  kafka:
    image: ubuntu/kafka
    ports:
    - "9092:9092"
    environment:
      ZOOKEEPER_HOST: 172.17.0.1
      ZOOKEEPER_PORT: 2181
  frontend:
    build:
      context: .
      dockerfile: dockerfile_frontend
    ports: 
    - "80:3000"
  worker:
    build:
      context: .
      dockerfile: dockerfile_worker
