FROM python
WORKDIR /frontend
ENV FLASK_APP=frontend.py
ENV FLASK_RUN_HOST=0.0.0.0
COPY requirements.txt requirements.txt
RUN pip install -r requirements.txt
EXPOSE 5000
COPY frontend.py frontend.py
CMD ["flask","run"]
